chore: first pass msi artifact
This is a combination of a a few substantial commits, and many debug commits.

diff --git a/.github/workflows/ci-base.yaml b/.github/workflows/ci-base.yaml
--- a/.github/workflows/ci-base.yaml
+++ b/.github/workflows/ci-base.yaml
@@ -190,6 +190,7 @@ jobs:
         run: |
           BINARY_HASH="${{ hashFiles(
             format('distributions/{0}/.goreleaser*.yaml', inputs.distribution),
+            format('distributions/{0}/windows/*', inputs.distribution),
             format('distributions/{0}/_build*/*', inputs.distribution)
           ) }}"
           ARGS_HASH=$(echo "${{ env.goreleaser_args }}" | sha256sum | cut -d' ' -f1)
@@ -215,6 +216,12 @@ jobs:
             echo "Tagging locally with $version to force goreleaser to use correct version in artifact names"
             git tag "$version"
           fi
+
+      - name: Setup wixl # Required to build MSI
+        if: inputs.publish || steps.cache-goreleaser.outputs.cache-hit != 'true'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y wixl
 
       - name: Build binaries & packages with GoReleaser
         if: inputs.publish || steps.cache-goreleaser.outputs.cache-hit != 'true'
@@ -253,6 +260,35 @@ jobs:
           else
             echo "image_tag=$VERSION-$ARCH" >> $GITHUB_ENV
           fi
+
+      # - name: Find MSI
+      #   id: find-msi
+      #   if: ${{ env.windows }}
+      #   run: |
+      #     cd distributions/${{ inputs.distribution }}
+      #     msi_artifact_name=${{ inputs.distribution }}_msi_${{ github.sha }}
+      #     msi_path="$(find dist/msi/${{inputs.distribution}}/*.msi)"
+      #     if [ ! -f $MSI_PATH ]; then
+      #       echo "❌ Error: .msi not found at $MSI_PATH"
+      #       exit 1
+      #     fi
+      #     echo "msi_path=$msi_path" >> $GITHUB_OUTPUT
+      #     echo "msi_artifact_name=$msi_artifact_name" >> $GITHUB_OUTPUT
+
+      # - name: Upload MSI Artifact
+      #   id: upload-msi
+      #   if: ${{ env.windows }}
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ steps.find-msi.outputs.msi_artifact_name }}
+      #     path: ${{ steps.find-msi.outputs.msi_path}}
+
+      # - name: Validate MSI
+      #   if: ${{ env.windows }}
+      #   uses: ./.github/workflows/ci-windows.yaml
+      #   with:
+      #     distribution: ${{ inputs.distribution }}
+      #     artifact: ${{ steps.find-msi.outputs.msi_artifact_name }}
 
       - name: Copy GoReleaser binary to Docker context
         id: copy-binary
@@ -395,7 +431,6 @@ jobs:
           echo "✅ Docker image SHA: ${docker_manifest_sha}"
           echo -n "${docker_manifest_sha}" > docker_manifest_sha
 
-
           # Set output names
           if [[ "${{ inputs.fips }}" == "true" ]]; then
             artifact_name="goreleaser_output_${{ inputs.distribution }}-fips_${{ github.sha }}"
@@ -412,7 +447,6 @@ jobs:
           echo "=== Artifact Structure [$artifact_name] ==="
           tree dist/ || find dist -type d | sort
 
-
       - name: Upload Artifacts
         if: ${{ !env.ACT && inputs.publish }}
         uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
@@ -421,4 +455,3 @@ jobs:
           path: |
             docker_manifest_sha
             dist
-
