chore: add validation of archives

diff --git a/.github/workflows/ci-base.yaml b/.github/workflows/ci-base.yaml
--- a/.github/workflows/ci-base.yaml
+++ b/.github/workflows/ci-base.yaml
@@ -228,16 +228,15 @@ jobs:
         if: steps.cache-goreleaser.outputs.cache-hit == 'true'
         run: echo "✅ GoReleaser build skipped - using cached binaries"
 
-      - name: Validate GoReleaser build files exist
+      - name: Validate GoReleaser build artifacts
         run: |
-          DIST_PATH="distributions/${{ inputs.distribution }}/dist"
-          if [ ! -d "$DIST_PATH" ]; then
+          cd "distributions/${{ inputs.distribution }}"
+          if [ ! -d "dist" ]; then
             echo "❌ $DIST_PATH not found!"
             exit 1
           fi
-          cd "$DIST_PATH"
           echo "📋 Checking for common files..."
-          files=("artifacts.json" "config.yaml" "metadata.json")
+          files=("dist/artifacts.json" "dist/metadata.json")
           missing_files=()
           for file in "${files[@]}"; do
             if [ ! -f "$file" ]; then
@@ -253,7 +252,7 @@ jobs:
             echo "✅ All common build files found!"
           fi
           echo "📋 Checking if binaries / executables exist..."
-          binary_dirs=($(find . -name "${{ inputs.distribution }}*_*" -type d))
+          binary_dirs=($(find dist -name "${{ inputs.distribution }}*_*" -type d))
           if [ ${#binary_dirs[@]} -eq 0 ]; then
             echo "❌ No binary directories found!"
             exit 1
@@ -278,6 +277,35 @@ jobs:
             echo "✅ All found directories contain binaries!"
           fi
           echo "binary_file=$BINARY_FILE" >> $GITHUB_ENV
+          echo "📋 Validating archives..."
+          archives=$( jq -r '.[] | select(.type == "Archive") | .path' dist/artifacts.json )
+          for archive in $archives; do
+            echo "Validating ${archive}"
+            if [ ! -f "${archive}" ]; then
+              echo "❌ ${archive} not found!"
+              exit 1
+            else
+              echo "  Found ${archive}"
+            fi
+            sum_file=$( jq -r ".[] | select(.type == \"Checksum\" and .extra.ChecksumOf == \"${archive}\") | .path" dist/artifacts.json )
+            if [ ! -f "${sum_file}" ]; then
+              echo "❌ ${$sum_file} not found!"
+              exit 1
+            else
+              echo "  Found ${sum_file}"
+            fi
+            archive_sum=$(sha256sum ${archive} | cut -d' ' -f1)
+            expected_sum=$(cat ${sum_file})
+            if [ "${archive_sum}" != "${expected_sum}" ]; then
+              echo "❌ Checksums do not match!"
+              echo "Checksum: ${archive_sum}"
+              echo "Expected: ${expected_sum}"
+              exit 1
+            else
+              echo "  Checksum validated"
+            fi
+          done
+          echo "✅ All archives validated!"
 
       - name: Extract relevant metadata
         run: |
