ci: fix nightly fips (#404)

diff --git a/.github/workflows/ci-base.yaml b/.github/workflows/ci-base.yaml
--- a/.github/workflows/ci-base.yaml
+++ b/.github/workflows/ci-base.yaml
@@ -74,7 +74,7 @@ jobs:
       - uses: docker/setup-buildx-action@v2
 
       - name: Install cross-compilation toolchain
-        if: inputs.fips == true
+        if: inputs.fips
         run: |
           sudo apt-get update
           sudo apt-get install -y \
@@ -86,7 +86,7 @@ jobs:
             libc6-dev-amd64-cross
 
       - name: Import GPG key
-        if: ${{github.event.pull_request.user.login != 'dependabot[bot]' }}
+        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
         id: import_gpg
         uses: crazy-max/ghaction-import-gpg@v6
         with:
@@ -94,7 +94,7 @@ jobs:
           passphrase: ${{ secrets.gpg_passphrase }}
 
       - name: Write GPG to path in memory for signing rpm/deb
-        if: ${{github.event.pull_request.user.login != 'dependabot[bot]' }}
+        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
         id: write_gpg_to_path
         run: |
           GPG_KEY_PATH="$(mktemp /dev/shm/gpg.XXXXXX)"
@@ -105,7 +105,7 @@ jobs:
 
       - name: Build Args
         run: |
-          if [ ${{ inputs.nightly }} = "true" && ${{ inputs.fips }} = "true" ]; then
+          if [ ${{ inputs.nightly }} = "true" ] && [ ${{ inputs.fips }} = "true" ]; then
             echo "goreleaser_args=--snapshot --clean --skip=publish,validate --timeout 2h --config .goreleaser-nightly-fips.yaml" >> $GITHUB_ENV
           elif [ ${{ inputs.nightly }} = "true" ]; then
             echo "goreleaser_args=--snapshot --clean --skip=publish,validate --timeout 2h --config .goreleaser-nightly.yaml" >> $GITHUB_ENV
@@ -138,7 +138,7 @@ jobs:
           ARCH=${ARCH@L}
           echo "version=$VERSION" >> $GITHUB_ENV
           echo "arch=$ARCH" >> $GITHUB_ENV
-          if [ ${{ inputs.nightly }} = "true" && ${{ inputs.fips }} = "true" ]; then
+          if [ ${{ inputs.nightly }} = "true" ] && [ ${{ inputs.fips }} = "true" ]; then
             echo "image_tag=$VERSION-nightly-fips-$ARCH" >> $GITHUB_ENV
           elif [ ${{ inputs.nightly }} = "true" ]; then
             echo "image_tag=$VERSION-nightly-$ARCH" >> $GITHUB_ENV
@@ -147,6 +147,27 @@ jobs:
           else
             echo "image_tag=$VERSION-$ARCH" >> $GITHUB_ENV
           fi
+
+      - name: Validate Usage of BoringCrypto
+        if: inputs.fips
+        run: |
+          ARCH=$(echo '${{ runner.arch }}' | sed 's/X/amd/g')
+          ARCH=${ARCH@L}
+          OS=$(echo '${{ runner.os }}')
+          OS=${OS@L}
+          printf -v BINARY_PATTERN "distributions/%s/dist/%s-fips_%s_%s*/*" "${{ inputs.distribution}}" "${{ inputs.distribution }}" "${OS}" "${ARCH}"
+          echo "Looking for binary pattern: ${BINARY_PATTERN}"
+          BINARY=$(find ${BINARY_PATTERN} 2>/dev/null | head -1)
+          if [[ -z "${BINARY}" ]]; then
+            echo "Error: Binary ${BINARY} not found"
+            exit 1
+          fi
+          go tool nm ${BINARY} | grep '_Cfunc__goboringcrypto_' || (echo 'fips distro should not use standard crypto' && exit 1)
+
+      - name: Validate FIPS ciphers 
+        if: inputs.fips
+        run: |
+          ./fips/validation/validate.sh "${{ secrets.registry }}/${{ inputs.distribution }}:${{ env.image_tag }}"
 
       - name: Setup local kind cluster
         uses: helm/kind-action@v1
@@ -160,28 +181,7 @@ jobs:
           kind load docker-image "${{ secrets.registry }}/${{ inputs.distribution }}:${{ env.image_tag }}" --name ${{ inputs.test_cluster_name }}
 
       - uses: azure/setup-helm@v4.2.0
-
-      - name: Validate Usage of BoringCrypto
-        if: inputs.fips == true
-        run: |
-          ARCH=$(echo '${{ runner.arch }}' | sed 's/X/amd/g')
-          ARCH=${ARCH@L}
-          OS=$(echo '${{ runner.os }}')
-          OS=${OS@L}
-          printf -v BINARY_PATTERN "distributions/%s/dist/%s-fips_%s_%s*/*" "${{ inputs.distribution}}" "${{ inputs.distribution }}" "${OS}" "${ARCH}"
-          echo "Looking for binary pattern: ${BINARY_PATTERN}"
-          BINARY=$(find ${BINARY_PATTERN} 2>/dev/null | head -1)
-          if [[ -z "${BINARY}" ]]; then
-            echo "Error"
-            exit 1
-          fi
-          go tool nm ${BINARY} | grep '_Cfunc__goboringcrypto_' || (echo 'fips distro should not use standard crypto' && exit 1)
-      
-      - name: Validate FIPS ciphers
-        if: inputs.fips == true
-        run: |
-          ./fips/validation/validate.sh "${{ secrets.registry }}/${{ inputs.distribution }}:${{ env.image_tag }}"
-
+ 
       - name: Run local e2e tests
         if: ${{ hashFiles(format('distributions/{0}/test/spec-local.yaml', inputs.distribution)) != '' }}
         uses: newrelic/newrelic-integration-e2e-action@v1
