feat: fips distributions (#387)
* feat: create fips versions of distributions

* feat: restructure so that both fips compliant and noncompliant versions of each distro is made

* feat: separate build.sh and .goreleaser.yaml into default and fips versions

* feat: change build-fips.sh so that instead of rebuilding the same thing over, just copy contents of _build into _build-fips

* Revert "feat: change build-fips.sh so that instead of rebuilding the same thing over, just copy contents of _build into _build-fips"

This reverts commit 600e08dfc7a1b98a9c1237a95d6d4264fc26bf3b.

_build-fips can't just copy over the contents of _build because _build-fips has it's own manifest-fips.yaml

* feat: edit configure.go to include fips

* feat: data agreement

* fix: fix bugs with Docker Images and Manifests

* fix: ran make generate-goreleaser

* feat: add fips version of files for new distro - nrdot-collector

* feat: add fips flag

* feat: add Dockerfile-fips files

* move fips flag further down configure.go stack

* use docker args

* standardize fips in configure.go and manifest files

* make build target dependent on build-fips target

* add ci-fips workflow

* add infrastructure to cross make ocb with cgo enabled

* adjust fips workflow, doesn't need tf

* bug squishing

* remove unnecessary toolchain dir

* chore: fips testing (#373)

* test: fix nightly (#363)

* feat: add e2e tests for core distro (#364)

* feat: add e2e tests for core distro

* chore: merge host config with core collector

* feat: Bump otel component versions from v0.128.0 to v0.131.0 (#357)

* chore: prep release 1.3.0 (#365)

* chore: Add nrdot-collector to release workflows (#366)

* chore: Add missing ec2 nightly deploy (#367)

* chore: Address cancelled deploy step (#370)

* feat: Add spanprocessor to nrdot-collector (#371)

* chore(deps): update helm release nr-k8s-otel-collector to v0.8.40 (#369)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* feat: Bump otel component versions from v0.131.0 to v0.132.0 (#368)

* chore: fips testing

* chore: test fips docker

* chore: cleaning up fips changes

---------

Co-authored-by: kb-newrelic <121687305+kb-newrelic@users.noreply.github.com>
Co-authored-by: otelcomm-bot <svc-otelcomm-bot@newrelic.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Emilia Ferreyra <110185663+emiliaFer@users.noreply.github.com>

* build details overrides

* git merged badly, fixing it

* update fips workflow

* add back fips configs

* updated goreleaser.yaml files

* add back fips go tags and ldflags

* fix directory in goreleaser-fips

* add boringcrypto validation

* update boring crypto validation

* add manifest-fips.yaml to .gitignore

* remove existing manifest-fips.yaml files

---------

Co-authored-by: mailo-nr <marsac@newrelic.com>
Co-authored-by: kb-newrelic <121687305+kb-newrelic@users.noreply.github.com>
Co-authored-by: otelcomm-bot <svc-otelcomm-bot@newrelic.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

diff --git a/.github/workflows/ci-base.yaml b/.github/workflows/ci-base.yaml
--- a/.github/workflows/ci-base.yaml
+++ b/.github/workflows/ci-base.yaml
@@ -10,6 +10,10 @@ on:
         required: false
         type: boolean
         default: false
+      fips:
+        required: false
+        type: boolean
+        default: false
       test_cluster_name:
         required: false
         type: string
@@ -70,6 +74,18 @@ jobs:
 
       - uses: docker/setup-buildx-action@v2
 
+      - name: Install cross-compilation toolchain
+        if: inputs.fips == true
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y \
+            gcc-aarch64-linux-gnu \
+            g++-aarch64-linux-gnu \
+            gcc-x86-64-linux-gnu \
+            g++-x86-64-linux-gnu \
+            libc6-dev-arm64-cross \
+            libc6-dev-amd64-cross
+
       - name: Import GPG key
         if: ${{github.event.pull_request.user.login != 'dependabot[bot]' }}
         id: import_gpg
@@ -92,6 +108,8 @@ jobs:
         run: |
           if [ ${{ inputs.nightly }} = "true" ]; then
             echo "goreleaser_args=--snapshot --clean --skip=publish,validate --timeout 2h --config .goreleaser-nightly.yaml" >> $GITHUB_ENV
+          elif [ ${{ inputs.fips }} = "true" ]; then
+            echo "goreleaser_args=--snapshot --clean --skip=publish,validate --timeout 2h --config .goreleaser-fips.yaml" >> $GITHUB_ENV
           elif [ ${{github.event.pull_request.user.login == 'dependabot[bot]' }} ]; then
             echo "goreleaser_args=--snapshot --clean --skip=publish,validate,sign --timeout 2h" >> $GITHUB_ENV
           else
@@ -121,6 +139,8 @@ jobs:
           echo "arch=$ARCH" >> $GITHUB_ENV
           if [ ${{ inputs.nightly }} = "true" ]; then
             echo "image_tag=$VERSION-nightly-$ARCH" >> $GITHUB_ENV
+          elif [ ${{ inputs.fips }} = "true" ]; then
+            echo "image_tag=$VERSION-fips-$ARCH" >> $GITHUB_ENV
           else
             echo "image_tag=$VERSION-$ARCH" >> $GITHUB_ENV
           fi
@@ -137,6 +157,22 @@ jobs:
           kind load docker-image "${{ secrets.registry }}/${{ inputs.distribution }}:${{ env.image_tag }}" --name ${{ inputs.test_cluster_name }}
 
       - uses: azure/setup-helm@v4.2.0
+
+      - name: Validate Usage of BoringCrypto
+        if: inputs.fips == true
+        run: |
+          ARCH=$(echo '${{ runner.arch }}' | sed 's/X/amd/g')
+          ARCH=${ARCH@L}
+          OS=$(echo '${{ runner.os }}')
+          OS=${OS@L}
+          printf -v BINARY_PATTERN "distributions/%s/dist/%s-fips_%s_%s*/*" "${{ inputs.distribution}}" "${{ inputs.distribution }}" "${OS}" "${ARCH}"
+          echo "Looking for binary pattern: ${BINARY_PATTERN}"
+          BINARY=$(find ${BINARY_PATTERN} 2>/dev/null | head -1)
+          if [[ -z "${BINARY}" ]]; then
+            echo "Error"
+            exit 1
+          fi
+          go tool nm ${BINARY} | grep '_Cfunc__goboringcrypto_' || (echo 'fips distro should not use standard crypto' && exit 1)
 
       - name: Run local e2e tests
         if: ${{ hashFiles(format('distributions/{0}/test/spec-local.yaml', inputs.distribution)) != '' }}
